### PR TITLE
fix(docs): research label instead of title

### PR DESCRIPTION
**Pull request by wesleytodd**
I propose we use labels instead of titles. This way we can use the GH filter specially made for this instead of a search. Not a big deal either way, but figured I would propose this as a PR. Also sorry I guess vs code defaults to adding a new line at the end of the file...not sure it matters to remove it though as that is a default setting I think most folks have right?

### CODE REVIEW

**Comment by wesleytodd** [comment]
Ok so I should have checked, but I don't even have permissions to add labels on here. I think those of us active in here should have that but I am not sure what additional permissions we need other than `member` status in the org. @rginn is there a process in place to members involved in these sub projects getting/managing permissions like this?

**Comment by rginn** [comment]
Hi! I just added @wesleytodd @darcyclarke and @lukekarrys as Admins. @Ethan-Arrowood was already an Admin. Please LMK if you need to add others.

**Comment by wesleytodd** [comment]
Awesome! And I think as admins we can add the other active folks as necessary. @Ethan-Arrowood are you alright with this label approach? It's not that big of a deal, and I thought it would be easy until I realized you cannot label unless you have a role in the repo/org, but maybe that is alright since it gives us the nice "sort view" in the issues listing?

**Review by Ethan-Arrowood — APPROVED** [review]
love it!

**Review by darcyclarke — APPROVED** [review]

**Pull request merged**
